// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package style

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Normalize() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n    /*! modern-normalize v3.0.1 | MIT License | https://github.com/sindresorhus/modern-normalize */\n    progress,\n    sub,\n    sup {\n        vertical-align: baseline\n    }\n\n    *,\n    ::after,\n    ::before {\n        box-sizing: border-box\n    }\n\n    html {\n        font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji';\n        line-height: 1.15;\n        -webkit-text-size-adjust: 100%;\n        tab-size: 4\n    }\n\n    body {\n        margin: 0\n    }\n\n    b,\n    strong {\n        font-weight: bolder\n    }\n\n    code,\n    kbd,\n    pre,\n    samp {\n        font-family: ui-monospace, SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;\n        font-size: 1em\n    }\n\n    small {\n        font-size: 80%\n    }\n\n    sub,\n    sup {\n        font-size: 75%;\n        line-height: 0;\n        position: relative\n    }\n\n    sub {\n        bottom: -.25em\n    }\n\n    sup {\n        top: -.5em\n    }\n\n    table {\n        border-color: currentcolor\n    }\n\n    button,\n    input,\n    optgroup,\n    select,\n    textarea {\n        font-family: inherit;\n        font-size: 100%;\n        line-height: 1.15;\n        margin: 0\n    }\n\n    [type=button],\n    [type=reset],\n    [type=submit],\n    button {\n        -webkit-appearance: button\n    }\n\n    legend {\n        padding: 0\n    }\n\n    ::-webkit-inner-spin-button,\n    ::-webkit-outer-spin-button {\n        height: auto\n    }\n\n    [type=search] {\n        -webkit-appearance: textfield;\n        outline-offset: -2px\n    }\n\n    ::-webkit-search-decoration {\n        -webkit-appearance: none\n    }\n\n    ::-webkit-file-upload-button {\n        -webkit-appearance: button;\n        font: inherit\n    }\n\n    summary {\n        display: list-item\n    }\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
