version: "3"

services:
  server:
    container_name: "server"
    build: .
    ports:
      - "8080:8080"
    volumes:
      - data:/data
    environment:
      JADE_DB_PATH: "/data/jade.db"

volumes:
  data:
    driver: local
